sonar.projectKey=navaneethan0312_node.app
sonar.organization=navaneethan0312
sonar.sources=.
sonar.exclusions=**/__tests__/**,**/node_modules/**,**/coverage/**
sonar.tests=__tests__
sonar.test.inclusions=**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
